[package]
name = "jeryu-runner-oci"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
jeryu-egress = { path = "../jeryu-egress" }
jeryu-runner-core = { path = "../jeryu-runner-core" }

[dev-dependencies]
anyhow = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
