[package]
name = "jeryu-runnerd"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
jeryu-ci-ir = { path = "../jeryu-ci-ir" }
jeryu-runner-core = { path = "../jeryu-runner-core" }
jeryu-runner-native = { path = "../jeryu-runner-native" }
jeryu-runner-microvm = { path = "../jeryu-runner-microvm" }
jeryu-runner-oci = { path = "../jeryu-runner-oci" }
jeryu-runner-protocol = { path = "../jeryu-runner-protocol" }
jeryu-runner-registry = { path = "../jeryu-runner-registry" }
serde = { workspace = true }

[lints]
workspace = true
